import type { Monaco } from '@monaco-editor/react';

const SQL_KEYWORDS = [
  'SELECT',
  'FROM',
  'WHERE',
  'AND',
  'OR',
  'NOT',
  'IN',
  'LIKE',
  'BETWEEN',
  'IS',
  'NULL',
  'TRUE',
  'FALSE',
  'AS',
  'ON',
  'JOIN',
  'LEFT',
  'RIGHT',
  'INNER',
  'OUTER',
  'FULL',
  'CROSS',
  'NATURAL',
  'USING',
  'ORDER',
  'BY',
  'ASC',
  'DESC',
  'NULLS',
  'FIRST',
  'LAST',
  'LIMIT',
  'OFFSET',
  'GROUP',
  'HAVING',
  'DISTINCT',
  'ALL',
  'UNION',
  'INTERSECT',
  'EXCEPT',
  'INSERT',
  'INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE',
  'CREATE',
  'TABLE',
  'DROP',
  'ALTER',
  'ADD',
  'COLUMN',
  'INDEX',
  'VIEW',
  'DATABASE',
  'SCHEMA',
  'PRIMARY',
  'KEY',
  'FOREIGN',
  'REFERENCES',
  'UNIQUE',
  'CHECK',
  'DEFAULT',
  'CONSTRAINT',
  'CASCADE',
  'RESTRICT',
  'TRUNCATE',
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'TRANSACTION',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'COALESCE',
  'NULLIF',
  'CAST',
  'CONVERT',
  'EXISTS',
  'ANY',
  'SOME',
];

const SQL_FUNCTIONS = [
  'COUNT',
  'SUM',
  'AVG',
  'MIN',
  'MAX',
  'ROUND',
  'FLOOR',
  'CEIL',
  'ABS',
  'UPPER',
  'LOWER',
  'TRIM',
  'LTRIM',
  'RTRIM',
  'LENGTH',
  'SUBSTRING',
  'CONCAT',
  'REPLACE',
  'POSITION',
  'LEFT',
  'RIGHT',
  'REVERSE',
  'NOW',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'DATE_PART',
  'DATE_TRUNC',
  'EXTRACT',
  'AGE',
  'INTERVAL',
  'ARRAY_AGG',
  'STRING_AGG',
  'JSON_AGG',
  'JSONB_AGG',
  'ROW_NUMBER',
  'RANK',
  'DENSE_RANK',
  'NTILE',
  'LAG',
  'LEAD',
  'FIRST_VALUE',
  'LAST_VALUE',
  'OVER',
  'PARTITION',
];

const SQL_TYPES = [
  'INT',
  'INTEGER',
  'BIGINT',
  'SMALLINT',
  'TINYINT',
  'MEDIUMINT',
  'DECIMAL',
  'NUMERIC',
  'REAL',
  'DOUBLE',
  'PRECISION',
  'FLOAT',
  'BOOLEAN',
  'BOOL',
  'CHAR',
  'VARCHAR',
  'TEXT',
  'DATE',
  'TIME',
  'DATETIME',
  'TIMESTAMP',
  'TIMESTAMPTZ',
  'INTERVAL',
  'UUID',
  'JSON',
  'JSONB',
  'ARRAY',
  'BYTEA',
  'SERIAL',
  'BIGSERIAL',
  'SMALLSERIAL',
  'MONEY',
  'AUTO_INCREMENT',
  'BLOB',
  'LONGTEXT',
  'MEDIUMTEXT',
  'ENUM',
  'SET',
];

export function registerSqlLanguage(monaco: Monaco): void {
  // Register SQL language if not already registered
  monaco.languages.register({ id: 'sql' });

  monaco.languages.registerCompletionItemProvider('sql', {
    provideCompletionItems: (model, position) => {
      const word = model.getWordUntilPosition(position);
      const lineContent = model.getLineContent(position.lineNumber);
      const textBeforeCursor = lineContent.slice(0, position.column - 1);
      const prefixMatch = textBeforeCursor.match(/[A-Za-z_][A-Za-z0-9_]*$/);

      const range = prefixMatch
        ? {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: prefixMatch.index! + 1,
            endColumn: position.column,
          }
        : {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn,
          };

      const currentWord = prefixMatch ? prefixMatch[0] : word.word;

      const suggestions = [
        ...SQL_KEYWORDS.filter((keyword) =>
          keyword.toLowerCase().startsWith(currentWord.toLowerCase()),
        ).map((keyword) => ({
          label: keyword,
          kind: monaco.languages.CompletionItemKind.Keyword,
          insertText: keyword,
          range,
          detail: 'SQL Keyword',
        })),
        ...SQL_FUNCTIONS.filter((fn) => fn.toLowerCase().startsWith(currentWord.toLowerCase())).map(
          (fn) => ({
            label: fn,
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: `${fn}($0)`,
            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
            range,
            detail: 'SQL Function',
          }),
        ),
        ...SQL_TYPES.filter((type) => type.toLowerCase().startsWith(currentWord.toLowerCase())).map(
          (type) => ({
            label: type,
            kind: monaco.languages.CompletionItemKind.TypeParameter,
            insertText: type,
            range,
            detail: 'SQL Data Type',
          }),
        ),
        {
          label: 'SELECT * FROM',
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: 'SELECT * FROM ${1:table_name} WHERE ${2:condition};',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
          detail: 'Select all from table',
          documentation: 'Basic SELECT statement',
        },
        {
          label: 'SELECT columns FROM',
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText:
            'SELECT ${1:column1}, ${2:column2}\nFROM ${3:table_name}\nWHERE ${4:condition}\nORDER BY ${5:column1}\nLIMIT ${6:10};',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
          detail: 'Select specific columns',
          documentation: 'SELECT with columns, WHERE, ORDER BY, and LIMIT',
        },
        {
          label: 'INSERT INTO',
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText:
            'INSERT INTO ${1:table_name} (${2:column1}, ${3:column2})\nVALUES (${4:value1}, ${5:value2});',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
          detail: 'Insert row',
          documentation: 'INSERT statement',
        },
        {
          label: 'UPDATE SET',
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText:
            'UPDATE ${1:table_name}\nSET ${2:column1} = ${3:value1}\nWHERE ${4:condition};',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
          detail: 'Update rows',
          documentation: 'UPDATE statement',
        },
        {
          label: 'DELETE FROM',
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: 'DELETE FROM ${1:table_name}\nWHERE ${2:condition};',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
          detail: 'Delete rows',
          documentation: 'DELETE statement',
        },
        {
          label: 'JOIN',
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText:
            'SELECT ${1:columns}\nFROM ${2:table1} t1\nJOIN ${3:table2} t2 ON t1.${4:id} = t2.${5:foreign_id}\nWHERE ${6:condition};',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
          detail: 'Join tables',
          documentation: 'JOIN statement',
        },
        {
          label: 'CREATE TABLE',
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText:
            'CREATE TABLE ${1:table_name} (\n  id SERIAL PRIMARY KEY,\n  ${2:column1} ${3:VARCHAR(255)} NOT NULL,\n  created_at TIMESTAMP DEFAULT NOW()\n);',
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
          detail: 'Create table',
          documentation: 'CREATE TABLE statement',
        },
      ];

      return { suggestions };
    },
    triggerCharacters: ['.', '(', ',', ' '],
  });
}

export function defineSqlTheme(monaco: Monaco): void {
  monaco.editor.defineTheme('db-playground-sql', {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'keyword', foreground: '576A8F', fontStyle: 'bold' },
      { token: 'keyword.sql', foreground: '576A8F', fontStyle: 'bold' },
      { token: 'string', foreground: 'FF7444' },
      { token: 'string.sql', foreground: 'FF7444' },
      { token: 'number', foreground: '22C55E' },
      { token: 'number.sql', foreground: '22C55E' },
      { token: 'comment', foreground: 'A0AEC0', fontStyle: 'italic' },
      { token: 'comment.sql', foreground: 'A0AEC0', fontStyle: 'italic' },
      { token: 'operator', foreground: '576A8F' },
      { token: 'operator.sql', foreground: '576A8F' },
      { token: 'predefined', foreground: '3B82F6' },
      { token: 'predefined.sql', foreground: '3B82F6' },
    ],
    colors: {
      'editor.background': '#FFFFFF',
      'editor.foreground': '#2D3748',
      'editor.lineHighlightBackground': '#FFF8DE40',
      'editorCursor.foreground': '#FF7444',
      'editor.selectionBackground': '#B7BDF750',
      'editorLineNumber.foreground': '#A0AEC0',
      'editorLineNumber.activeForeground': '#576A8F',
      'editor.inactiveSelectionBackground': '#B7BDF730',
      'editorIndentGuide.background': '#E2E8F0',
      'editorIndentGuide.activeBackground': '#B7BDF7',
    },
  });
}
